### ISSUE TITLE
"azurestorageemulator" is out of date

### ISSUE THREAD

**Issue by TomBonnerAtTFL** [erichexter/ChocolateyPackages#2]
Hi

`azurestorageemulator` has been updated to 5.9 and we'd like to use Chocolatey to install it. I'll include a PR to do the change. If you could update the package that'd be really helpful.

I can also offer to become a fellow maintainer of this package if that'd be helpful?

Tom

**Comment by erichexter** [comment]
Tom, thanks for the pull request. I merged it, packed and pushed it to chocolatey.org.  I think it will be under moderation for now. Please send your chocolatey ID and I can add you as a maintainer to this package. I would not turn down a helping hand.

**Comment by TomBonnerAtTFL** [comment]
Hi @erichexter 

My Chocolatey ID is also TomBonnerAtTfL. Hope I can help.

Tom
